# Services definition for building & deploying

services:

  # Zitadel
  zitadel:
    # Build
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:latest}
    # Deploy
    command:
      - start-from-setup
      - --masterkey
      - ${ZITADEL_MASTER_KEY:-MasterkeyNeedsToHave32Characters}
    environment:
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-zitadel.localhost}
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT:-443}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE:-true}
      ZITADEL_TLS_ENABLED: ${ZITADEL_TLS_ENABLED:-false}
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST:-localhost}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT:-5432}
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${DB_NAME:-zitadel_db}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${DB_USER:-zitadel_db_user}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${DB_PASSWORD:-zitadel_db_password}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ${DB_SSL_MODE:-disable}
    ports:
      # HTTP
      - ${HTTP_PORT:-443}:${ZITADEL_EXTERNALPORT:-443}
