# Services definition for building & deploying

services:

  # Zitadel
  zitadel:
    # Build
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:latest}
    # Deploy
    command:
      - start-from-setup
      - --masterkeyFromEnv
    environment:
      # Zitadel configuration
      ZITADEL_MASTERKEY: ${ZITADEL_MASTERKEY:-MasterkeyNeedsToHave32Characters}
      ZITADEL_PORT: ${DOCKER_PORT:-8080}
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT:-443}
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-zitadel.localhost}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE:-true}
      ZITADEL_TLS_ENABLED: ${ZITADEL_TLS_ENABLED:-false}
      # Zitadel system admin configuration
      ZITADEL_SYSTEMAPIUSERS: ${ZITADEL_SYSTEMAPIUSERS:-}
      # Database configuration
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST:-localhost}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT:-5432}
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${DB_NAME:-zitadel_db}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${DB_USER:-zitadel_db_user}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${DB_PASSWORD:-zitadel_db_password}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ${DB_SSL_MODE:-disable}
    ports:
      - ${HTTP_PORT:-80}:${DOCKER_PORT:-8080} # HTTP
