# Services definition override for development

services:

  # Database
  db:
    # Extend
    extends:
      file: docker-compose-db.yml
      service: db
    # Deploy override
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres_password}

  # Zitadel Init
  zitadel-init:
    # Deploy override
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database configuration override
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST:-db}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT:-5432}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ${DB_SSL_MODE:-disable}
      # Database init configuration override
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${DB_ADMIN_USER:-postgres}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres_password}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE:-disable}

  # Zitadel Setup
  zitadel-setup:
    # Deploy override
    environment:
      # Database configuration override
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST:-db}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT:-5432}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ${DB_SSL_MODE:-disable}
      # Database init configuration override
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${DB_ADMIN_USER:-postgres}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres_password}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE:-disable}

  # Zitadel
  zitadel:
    # Deploy override
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Zitadel system admin configuration
      ZITADEL_SYSTEMAPIUSERS: >
        {
          "system-test-user": {
            "Path": "/system-test-user.pub"
          }
        }
      # Database configuration override
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST:-db}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT:-5432}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ${DB_SSL_MODE:-disable}
      # Database init configuration override
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${DB_ADMIN_USER:-postgres}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres_password}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE:-disable}
    volumes:
      - ./zitadel-config/system-test-user.pub:/system-test-user.pub:ro
