# Services definition for building & deploying

services:

  # Zitadel
  zitadel:
    # Build
    image: ghcr.io/zitadel/zitadel:latest
    # Deploy
    command:
      - start-from-init
      - --masterkey
      - ${ZITADEL_MASTER_KEY:-MasterkeyNeedsToHave32Characters}
    environment:
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-zitadel.localhost}
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT:-443}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE:-true}
      ZITADEL_TLS_ENABLED: ${ZITADEL_TLS_ENABLED:-false}
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST:-localhost}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT:-5432}
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${DB_NAME:-zitadel}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${DB_USER:-zitadel}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${DB_PASSWORD:-zitadel}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: ${DB_SSL_MODE:-disable}
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${DB_ADMIN_USER:-postgres}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE:-disable}
    ports:
      # HTTP
      - ${HTTP_PORT:-443}:${HTTP_DOCKER_PORT:-443}
