# Services definition override for development

services:

  # Database
  db:
    # Build
    image: postgres:16.3-alpine
    # Deploy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zitadel_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

  # Zitadel
  zitadel:
    # Deploy override
    command:
      - start-from-init
      - --masterkeyFromEnv
      - --tlsMode
      - disabled
    depends_on:
      db:
        condition: 'service_healthy'
    environment:
      # Zitadel configuration
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT:-8080}
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-localhost}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE:-false}
      ZITADEL_TLS_ENABLED: ${ZITADEL_TLS_ENABLED:-false}
      # Database configuration
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel_db
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel_db_user
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel_db_password
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
    ports: !reset null
    ports:
      # HTTP
      - ${HTTP_PORT:-80}:${ZITADEL_PORT:-8080}
