# Services definition for database building & deploying

services:

  # Database
  db:
    # Build
    image: postgres:16.3-alpine
    # Deploy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zitadel_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel_db", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
