# Services definition override for development

services:

  # Database
  db:
    # Extend
    extends:
      file: docker-compose-db.yml
      service: db

  # Zitadel Init
  zitadel-init:
    # Build
    image: ${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:latest}
    # Deploy
    user: ${UID:-1000}
    command: init --config /zitadel.yaml
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Zitadel configuration
      ZITADEL_EXTERNALDOMAIN: zitadel-127.0.0.1.sslip.io
      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: true
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      # Database configuration
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel_db
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel_db_user
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel_db_password
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
    healthcheck:
      test: [ "CMD", "/app/zitadel", "ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Zitadel
  zitadel:
    # Deploy override
    user: ${UID:-1000}
    command:
      - start-from-setup
      - --init-projections
      - --masterkeyFromEnv
      - --config
      - /zitadel.yaml
      - --steps
      - /zitadel.yaml
    depends_on:
      db:
        condition: service_healthy
      zitadel-init:
        condition: service_completed_successfully
    environment:
      # Zitadel configuration
      ZITADEL_PORT: 8080
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-zitadel-127.0.0.1.sslip.io}
      ZITADEL_EXTERNALPORT: ${HTTP_PORT:-443}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE:-true}
      ZITADEL_TLS_ENABLED: ${ZITADEL_TLS_ENABLED:-false}
      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: true
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      ZITADEL_SYSTEMAPIUSERS: >
        {
          "system-test-user": {
            "Path": "/system-test-user.pub"
          }
        }
      # Database configuration
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel_db
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel_db_user
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel_db_password
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
    healthcheck:
      test: [ "CMD", "/app/zitadel", "ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports: !reset null
    volumes:
      - ./zitadel-config/system-test-user.pub:/system-test-user.pub:ro

  # Caddy Proxy
  proxy:
    # Build
    image: caddy:latest
    # Deploy
    volumes:
      - ./caddy-config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config/zitadel/selfsigned.crt:/etc/certs/zitadel/selfsigned.crt:ro
      - ./caddy-config/zitadel/selfsigned.key:/etc/certs/zitadel/selfsigned.key:ro
      - ./caddy-config/alpha/selfsigned.crt:/etc/certs/alpha/selfsigned.crt:ro
      - ./caddy-config/alpha/selfsigned.key:/etc/certs/alpha/selfsigned.key:ro
      - ./caddy-config/beta/selfsigned.crt:/etc/certs/beta/selfsigned.crt:ro
      - ./caddy-config/beta/selfsigned.key:/etc/certs/beta/selfsigned.key:ro
    ports:
      - ${HTTP_PORT:-443}:443 # HTTPS
    depends_on:
      zitadel:
        condition: service_healthy
