# Services definition override for initialization

services:

  # Zitadel
  zitadel:
    # Deploy override
    command: [ "init", "--config", "/zitadel.yaml" ]
    healthcheck:
      test: [ "CMD", "/app/zitadel", "ready" ]
      interval: '10s'
      timeout: '5s'
      retries: 5
      start_period: '10s'
    environment:
      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: ${ZITADEL_LOGS:-true}
      ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE: ${DB_ADMIN_NAME:-}
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${DB_ADMIN_USER:-}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD:-}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: ${DB_ADMIN_SSL_MODE:-}
    ports: !reset null
